#!/usr/bin/env python3

import sys, os
from PyQt5.QtWidgets import QApplication, QMessageBox
from lolforlinuxinstaller import Installer

if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.setDesktopFileName("lolforlinuxinstaller")
    if os.getuid() == 0:
        msg_box = QMessageBox()
        msg_box.setText("Don't run this as sudo user")
        msg_box.exec_()
        sys.exit(1)

    installer = Installer()
    installer.show()
    sys.exit(app.exec_())
